/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DAM2_02
 */
public class BotonEscurridizo extends javax.swing.JFrame {

    /**
     * Creates new form BotonEscurridizo
     */
    int turnos;

    public BotonEscurridizo() {
        initComponents();
        turnos = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonMover = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        botonMover.setBackground(new java.awt.Color(246, 232, 198));
        botonMover.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        botonMover.setForeground(new java.awt.Color(218, 91, 4));
        botonMover.setText("¡ATRÁPAME!");
        botonMover.setPreferredSize(new java.awt.Dimension(120, 25));
        botonMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMoverMouseEntered(evt);
            }
        });
        botonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMoverActionPerformed(evt);
            }
        });
        getContentPane().add(botonMover);
        botonMover.setBounds(140, 187, 130, 30);

        fondo.setBackground(new java.awt.Color(216, 194, 170));

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMoverActionPerformed
        JOptionPane.showMessageDialog(this, "¡Lo atrapaste en " + turnos + "! 🎉");
    }//GEN-LAST:event_botonMoverActionPerformed

    private void botonMoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMoverMouseEntered
        turnos++;
        Timer timer = new Timer(150, new ActionListener() { // Espera 500ms antes de moverse
            @Override
            public void actionPerformed(ActionEvent e) {
                Random random = new Random();
                int maxX = getContentPane().getWidth() - botonMover.getWidth();
                int maxY = getContentPane().getHeight() - botonMover.getHeight();

                int x = random.nextInt(Math.max(maxX, 1));
                int y = random.nextInt(Math.max(maxY, 1));

                botonMover.setLocation(x, y);
            }
        });
        timer.setRepeats(false); // Para que solo se ejecute una vez
        timer.start();
    }//GEN-LAST:event_botonMoverMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonEscurridizo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMover;
    private javax.swing.JPanel fondo;
    // End of variables declaration//GEN-END:variables
}
