/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VistaControlador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author DAM2_02
 */
public class BotonEscurridizo extends javax.swing.JFrame {

    /**
     * Creates new form BotonEscurridizo
     */
    int turnos;
    private MenuMinijuegos mm;

    public BotonEscurridizo() {
        initComponents();
        turnos = 0;
    }
    
    public BotonEscurridizo(MenuMinijuegos mm) {
        initComponents();
        this.mm = mm;
        turnos = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        botonRindo = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        botonMover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        fondo.setBackground(new java.awt.Color(216, 194, 170));
        fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        botonRindo.setBackground(new java.awt.Color(246, 232, 198));
        botonRindo.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        botonRindo.setForeground(new java.awt.Color(218, 91, 4));
        botonRindo.setText("RENDIRSE");
        botonRindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRindoActionPerformed(evt);
            }
        });

        msg.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        msg.setForeground(new java.awt.Color(35, 103, 114));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setText("¡INTENTA ATRAPAR EL BOTÓN!");

        botonMover.setBackground(new java.awt.Color(249, 201, 107));
        botonMover.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        botonMover.setForeground(new java.awt.Color(35, 103, 114));
        botonMover.setText("¡ATRÁPAME!");
        botonMover.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(129, 69, 44), 0, true));
        botonMover.setFocusPainted(false);
        botonMover.setPreferredSize(new java.awt.Dimension(120, 25));
        botonMover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMoverMouseEntered(evt);
            }
        });
        botonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(msg))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(botonMover, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(botonRindo)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(msg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(botonMover, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(botonRindo)
                .addGap(34, 34, 34))
        );

        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 400, 400);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMoverActionPerformed
        Ventana_Puntos vn = new Ventana_Puntos(turnos, mm);
        vn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonMoverActionPerformed

    private void botonMoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMoverMouseEntered
        turnos++;
        Timer timer = new Timer(150, new ActionListener() { // Espera 500ms antes de moverse
            @Override
            public void actionPerformed(ActionEvent e) {
                Random random = new Random();
                int maxX = getContentPane().getWidth() - botonMover.getWidth();
                int maxY = getContentPane().getHeight() - botonMover.getHeight();

                int x = random.nextInt(Math.max(maxX, 1));
                int y = random.nextInt(Math.max(maxY, 1));

                botonMover.setLocation(x, y);
            }
        });
        timer.setRepeats(false); // Para que solo se ejecute una vez
        timer.start();
    }//GEN-LAST:event_botonMoverMouseEntered

    private void botonRindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRindoActionPerformed
       this.dispose();
       mm.setVisible(true);
    }//GEN-LAST:event_botonRindoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonEscurridizo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonEscurridizo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonMover;
    private javax.swing.JButton botonRindo;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
